### ISSUE TITLE
Action not firing! 

### ISSUE THREAD

**Issue by AndyObtiva** [ankor-io-deprecated/ankor-framework#3]
In my JS Client application for a Java back-end server running with Ankor and a standard WebSocketEndPoint, I am having a problem with an action (tied to a method with @ActionListener on it without params) not firing anymore after a certain user interaction scenario. It does fire before that scenario is followed. I am guessing the scenario is causing an exception that is getting eaten and hidden somewhere. The symptom however is I see an Out message in the JS console containing the correct data for firing the action, but I never see the response In message. When I debugged the Java server, I was able to trace that JS Out message going into the Java Ankor library all the way to Akka and then disappearing, not firing my "login" action. Could it be possibly Akka dead letters? I checked the log and did not see anything under INFO as mentioned in the Akka documentation of dead letters.

Any advice on how to diagnose this further or a workaround/solution if you've encountered before would be greatly appreciated.

**Comment by manolitto** [comment]
I don't think the event is lost in Akka dead letters... I guess there might be a problem with the ActionListener? You could try to find out be setting a breakpoint in SimpleEventDispatcher (all EventDispatcher variants internally delegate to SimpleEventDispatcher so eventually every event is dispatched from there).
You may check if there is an appropriate listener in the current eventListeners list and debug the listeners loop for checking if "isAppropriateListener" is called at all on any listener and if there is any listener that is invoked for the action event.
Perhaps the ActionListener annotation is not working? How do you instantiate your model bean? Directly via constructor or with a BeanFactory?

**Comment by AndyObtiva** [comment]
Thanks. I troubleshooted further and found out that on subsequent invocations of the "login" action, there is no ViewModelActionEventListener in the loop checking for isAppropriateListener. It does exist however on the first "login" action (happens in the original Ankor session before refreshing the web page and reconnecting to the same ViewModel on a new session).

Here are more details that might help you understand what is causing this.

I have this code in my WebApplication extends GenericApplication class:

<pre><code>
   @Override
   public void shutdown() {
      /* No cleanup necessary since we are maintaining models for long sessions */
   }
   @Override
   public void releaseModel(String modelName, Object modelRoot) {
      ModelRoot root = (ModelRoot)modelRoot;
      if (!root.getLoginViewModel().getLoggedInUserModel().getRememberMe()) {
         super.releaseModel(modelName, modelRoot);
      }
   }
</code></pre>

And here is the scenario that causes the problem.

The first time I visit the web page, I login with "rememberMe" checked. Login action works as expected triggering the "login" method on the LoginViewModel.
I refresh the page, and the Ankor session ends without releasing the model since I checked "rememberMe"
The new Ankor session reloads the right model with lookupModel given I am passing the same (cookie-stored) value for "at.irian.ankor.MODEL_INSTANCE_ID" under connectParams (as passed to the ankor system transport)
Finally, if I try to change user in the application by bringing up the login window and entering info for a new user, clicking the "login" button to trigger the "login" action does nothing.

It is almost like restarting the Ankor session and using it with an existing model from a previous session ends up with no action listener registered on the LoginViewModel "login" method anymore. My theory is that closing the session somehow caused removal of that listener from the model. I tried tracing that in the code, and found this snippet under ActionListenersPostProcessor:

```
    for (EventListener eventListener : eventListeners) {
        if (eventListener instanceof ViewModelActionEventListener) {
            if (((ViewModelActionEventListener) eventListener).getWatchedProperty().equals(beanRef)) {
                // ... and discard it
                eventListeners.remove(eventListener);
                break;
            }
        }
    }
```

I am guessing it is responsible, but then debugging did not result in hitting it after the first login.

Before I troubleshoot further, I figured I'd share my findings with you in case you have another hint or idea as to what might be causing this.

About your questions: 

"Perhaps the ActionListener annotation is not working?"

Yes, that seems to be the case.

" How do you instantiate your model bean? Directly via constructor or with a BeanFactory?"

My model bean is instantiated directly under ModelRoot with the following code:

<pre><code>
   public ModelRoot(Ref rootRef) {
      this.rootRef = rootRef;
      this.loginViewModel = new LoginViewModel(rootRef.appendPath("loginViewModel"));
      this.setVersion(fetchVersion()); //must initialize before Ankor reads the view model in the call below
      
      AnkorPatterns.initViewModel(this, rootRef);
   }
</code></pre>

ModelRoot itself is instantiated in GenericApplication.

Thanks for responding very quickly. I hope you and your loved ones are enjoying the holidays. I look forward to your next answer.

Regards,

Andy

**Comment by AndyObtiva** [comment]
OK, after a lot of debugging, I finally figured it out. The DefaultServerRoutingLogic.getOrCreateStatefulSession method is forgetting to re-initialize models with a new Ref when found through application.lookupModel after starting a new Model session.

To fix, I hacked my WebApplication with a lookupModel that intentionally returns null, and then overrode createModel as follows:

<pre><code>
   @Override
   public Object createModel(String modelName, Map<String, Object> connectParameters, RefContext refContext) {      
      Object model = lookupOldModel(modelName, connectParameters);
      if (model == null) {
         model = createNewModel(modelName, connectParameters, refContext);
      } 
      else {
         RefModel refModel = (RefModel)model;
         refModel.initialize(refContext.refFactory().ref(modelName));
      }
      return model;
   }
</code></pre>

The refModel.initialize method takes care of re-running AnkorPatterns.initViewModel on the ModelRoot and all sub-models.

I had a lot of trouble coming up with a cleaner fix, such as providing my own ServerRoutingLogic or ModelSessionManager/Factory because the methods responsible for overriding them were private (sometimes it felt overkill to not have them protected). Also, I wish I could supply a class for them as an alternative to an instance. There were methods that allowed me to inject an instance, but then I couldn't get the parameters needed for initializing them before passing them in because the parameters were generated inside the AnkorSystemBuilder like in these two lines:

```
    ModelSessionFactory modelSessionFactory = getModelSessionFactory(eventDispatcherFactory,
                                                                     defaultEventListeners,
                                                                     refContextFactory,
                                                                     application);

    ModelSessionManager modelSessionManager = getServerModelSessionManager(modelSessionFactory,
                                                                           application);
```

Also, there were no withModelSessionFactory or withModelSessionManager methods, and the withRoutingLogic was a client-only routing logic override.

Sorry if I am venting some frustration. I understand the APIs are growing on a per-need basis, so I hope the feedback I am providing helps.

By the way, in order to re-initialize my view models cleanly, I had them extend a new class I created, RefModel (implementing RefAware), and follow the Composite pattern to allow re-initialization recursively with one call.

Here is my RefModel should any of it be potentially useful for the Ankor project:

<pre><code>
public abstract class RefModel implements RefAware {
   private List<RefModel> children = new ArrayList<>();
   private String refPath;
   private Ref ref;
   public RefModel(String refPath) {
      this.refPath = refPath;
   }
   
   public String getRefPath() {
      return refPath;
   }
   
   public Ref getRef() {
      return ref;
   }
   
   protected void addChild(RefModel child) {
      this.children.add(child);
   }
   
   /**
    * Returns any sub-ref-models
    * @return children of ref model if any or an empty list otherwise
    */
   public List<RefModel> getChildren() {
      return Collections.unmodifiableList(children);
   }
   
   /**
    * Initializes this Ankor Ref and all children's as well 
    * @param rootRef
    */
   public void initialize(Ref rootRef) {
      this.ref = rootRef;
      if (this.refPath != null) {         
         this.ref = this.ref.appendPath(this.refPath);
      }
      AnkorPatterns.initViewModel(this, this.ref);
      this.children.forEach(model -> model.initialize(rootRef));
   }
   
}
</code></pre>

Here is the refactored ModelRoot constructor:

<pre><code>
   public ModelRoot(Ref rootRef) {
      super(null);
      this.loginViewModel = new LoginViewModel("loginViewModel");
      super.addChild(loginViewModel);
      this.setVersion(fetchVersion()); //must initialize before Ankor reads the view model in the call below
      
      initialize(rootRef);
   }
</code></pre>

And, here is an example of a sub-model:constructor:

<pre><code>
   public LoginViewModel(String refPath) {
      super(refPath);
      this.loginModelView = new LoginModelView();
      this.loggedInUserModel = new LoggedInUserModel("loginViewModel.loggedInUserModel");
      super.addChild(loggedInUserModel);
   }
</code></pre>

The code has several areas with potential room for improvement, such as templating the constructor (Template Method pattern) and not requiring absolute ref paths, but I figured I'd share anyways.

Thanks again for providing me with hints on what to look for, and hope we'd see a fix for this soon in the next release of Ankor.

**Comment by AndyObtiva** [comment]
I'm keeping this issue open until there is a clean official fix in the Ankor library classes.

**Comment by AndyObtiva** [comment]
I forked the codebase to contribute my fix for this as well as my ViewModel abstract class. I noticed there is already a ViewModelBase, so I renamed mine to CompositeViewModelBase since it represents composite view models. You'll see the details when I submit a Pull Request

**Comment by AndyObtiva** [comment]
I submitted some of the solution code I felt was useful publicly, in this pull request:
https://github.com/ankor-io/ankor-framework/pull/4

I might submit another pull request with the rest of the fix as part of a new StatefulWebApplicaiton class perhaps. I am closing this ticket for the moment given I am addressing the code details in pull requests. 

Thanks again for your prompts responses.
